[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19"

[dev]
  command = "npm run dev"
  targetPort = 5173

# Environment variables for API integrations
# GEMINI_API_KEY: Your Google Gemini API key (set in Netlify dashboard)
# This key is used securely in serverless functions and never exposed to the frontend
