[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.1.0",
    "fastapi>=0.118.0",
    "flask>=3.1.2",
    "pydantic>=2.11.10",
    "uvicorn>=0.37.0",
]
